#!/usr/bin/env bash
set -euo pipefail

# End-to-end CLOUD lifecycle test:
# company -> manager -> employee -> schedule -> shift (+ RLS checks)
#
# This script uses:
# - Edge Functions: create_company_with_manager, create_employee_login
# - Supabase Auth: password grant for access tokens
# - PostgREST (direct table inserts/selects) for employees, job_sites, schedules, shifts
#
# No secrets are committed. Provide these via env vars before running.
#
# Required env:
#   SUPABASE_ANON_KEY               (public anon key)
#   PLATFORM_ADMIN_PIN              (4-digit PIN; will prompt if not set)
#
# Optional env (override defaults):
#   PLATFORM_ADMIN_COMPANY_CODE     (default: PLATFORM)
#   PLATFORM_ADMIN_EMAIL            (if set, used directly; otherwise internal email is derived)
#   PLATFORM_ADMIN_USERNAME         (required if PLATFORM_ADMIN_EMAIL is not set)
#   COMPANY_A_CODE / COMPANY_B_CODE (if not set, autogenerated)
#   MANAGER_A_USERNAME / MANAGER_B_USERNAME
#   MANAGER_A_PIN / MANAGER_B_PIN
#   EMPLOYEE_1_USERNAME / EMPLOYEE_1_PIN
#   EMPLOYEE_2_USERNAME / EMPLOYEE_2_PIN
#
# Usage:
#   export SUPABASE_ANON_KEY='...'
#   export PLATFORM_ADMIN_EMAIL='admin@example.com'   # or set PLATFORM_ADMIN_USERNAME (+ PLATFORM company)
#   export PLATFORM_ADMIN_PIN='1234'
#   ./scripts/cloud_lifecycle_test.sh

PROJECT_REF="$(cat supabase/.temp/project-ref 2>/dev/null || true)"
if [[ -z "${PROJECT_REF}" ]]; then
  echo "Missing supabase/.temp/project-ref (run: supabase link --project-ref ...)" >&2
  exit 1
fi

EXPECTED_PROJECT_REF="xwroayzhbbwbiuswtuvs"
if [[ "${PROJECT_REF}" != "${EXPECTED_PROJECT_REF}" ]]; then
  echo "Refusing to run: expected Cloud project ${EXPECTED_PROJECT_REF}, got ${PROJECT_REF}" >&2
  exit 1
fi

BASE_URL="https://${PROJECT_REF}.supabase.co"
FUNCTIONS_URL="https://${PROJECT_REF}.functions.supabase.co"

: "${SUPABASE_ANON_KEY:?Set SUPABASE_ANON_KEY (public anon key)}"

PLATFORM_ADMIN_COMPANY_CODE="${PLATFORM_ADMIN_COMPANY_CODE:-PLATFORM}"
PLATFORM_ADMIN_EMAIL="${PLATFORM_ADMIN_EMAIL:-}"
PLATFORM_ADMIN_USERNAME="${PLATFORM_ADMIN_USERNAME:-}"
PLATFORM_ADMIN_PIN="${PLATFORM_ADMIN_PIN:-}"

ts="$(date -u +%Y%m%d%H%M%S)"
rand="${RANDOM:-0}"

COMPANY_A_CODE="${COMPANY_A_CODE:-E2EA$((rand % 900 + 100))}"
COMPANY_B_CODE="${COMPANY_B_CODE:-E2EB$((rand % 900 + 100))}"

MANAGER_A_USERNAME="${MANAGER_A_USERNAME:-managera}"
MANAGER_B_USERNAME="${MANAGER_B_USERNAME:-managerb}"
MANAGER_A_PIN="${MANAGER_A_PIN:-}"
MANAGER_B_PIN="${MANAGER_B_PIN:-}"

EMPLOYEE_1_USERNAME="${EMPLOYEE_1_USERNAME:-employee1}"
EMPLOYEE_1_PIN="${EMPLOYEE_1_PIN:-}"
EMPLOYEE_2_USERNAME="${EMPLOYEE_2_USERNAME:-employee2}"
EMPLOYEE_2_PIN="${EMPLOYEE_2_PIN:-}"

COMPANY_A_NAME="${COMPANY_A_NAME:-E2E Company A ${ts}}"
COMPANY_B_NAME="${COMPANY_B_NAME:-E2E Company B ${ts}}"

if ! command -v jq >/dev/null 2>&1; then
  echo "This script requires jq (for safe parsing without printing tokens)." >&2
  exit 1
fi

require_value() {
  local name="$1"
  local prompt="$2"
  local secret="${3:-0}"

  if [[ -n "${!name:-}" ]]; then
    return 0
  fi

  if [[ ! -t 0 ]]; then
    echo "Missing ${name} and no TTY available. Export ${name} and re-run." >&2
    exit 1
  fi

  if [[ "$secret" == "1" ]]; then
    read -s -p "${prompt}: " "$name"
    echo
  else
    read -r -p "${prompt}: " "$name"
  fi
}

print_redacted_json() {
  local label="$1"
  local raw="$2"
  echo "${label}:" >&2
  echo "$raw" | jq 'del(.access_token, .refresh_token, .provider_token, .provider_refresh_token, .pin, .managerPin, .newPin)' \
    >&2 || echo "$raw" >&2
}

internal_email() {
  local company_code="$1"
  local username="$2"
  echo "${company_code}+${username}@yourapp.local"
}

auth_password_grant() {
  local email="$1"
  local password="$2"

  curl -sS -X POST \
    "${BASE_URL}/auth/v1/token?grant_type=password" \
    -H "apikey: ${SUPABASE_ANON_KEY}" \
    -H "content-type: application/json" \
    --data-binary "$(
      printf '{"email":"%s","password":"%s"}' "$email" "$password"
    )"
}

call_function() {
  local function_name="$1"
  local bearer="$2"
  local json_body="$3"

  curl -sS -X POST \
    "${FUNCTIONS_URL}/${function_name}" \
    -H "apikey: ${SUPABASE_ANON_KEY}" \
    -H "authorization: Bearer ${bearer}" \
    -H "content-type: application/json" \
    --data-binary "$json_body"
}

rest_select() {
  local bearer="$1"
  local path_and_query="$2"
  curl -sS \
    "${BASE_URL}/rest/v1/${path_and_query}" \
    -H "apikey: ${SUPABASE_ANON_KEY}" \
    -H "authorization: Bearer ${bearer}"
}

rest_insert() {
  local bearer="$1"
  local table="$2"
  local json_body="$3"
  curl -sS -X POST \
    "${BASE_URL}/rest/v1/${table}" \
    -H "apikey: ${SUPABASE_ANON_KEY}" \
    -H "authorization: Bearer ${bearer}" \
    -H "content-type: application/json" \
    -H "prefer: return=representation" \
    --data-binary "$json_body"
}

echo "Using project: ${PROJECT_REF}"
echo "Company A code: ${COMPANY_A_CODE}"
echo "Company B code: ${COMPANY_B_CODE}"

echo ""
echo "1) Sign in as platform_admin (company=${PLATFORM_ADMIN_COMPANY_CODE})"
require_value "PLATFORM_ADMIN_PIN" "PLATFORM_ADMIN_PIN (4 digits)" 1
if [[ -z "$PLATFORM_ADMIN_EMAIL" ]]; then
  require_value "PLATFORM_ADMIN_USERNAME" "PLATFORM_ADMIN_USERNAME (for internal email)" 0
  pa_email="$(internal_email "${PLATFORM_ADMIN_COMPANY_CODE}" "${PLATFORM_ADMIN_USERNAME}")"
else
  pa_email="$PLATFORM_ADMIN_EMAIL"
fi
echo "   platform_admin email: ${pa_email}"
pa_auth="$(auth_password_grant "$pa_email" "$PLATFORM_ADMIN_PIN")"
PA_TOKEN="$(echo "$pa_auth" | jq -r '.access_token // empty')"
PA_USER_ID="$(echo "$pa_auth" | jq -r '.user.id // empty')"
if [[ -z "${PA_TOKEN}" || -z "${PA_USER_ID}" ]]; then
  print_redacted_json "Failed to sign in as platform_admin" "$pa_auth"
  exit 1
fi
echo "   platform_admin auth user id: ${PA_USER_ID}"

echo ""
echo "2) Create Company A + Manager A via Edge Function create_company_with_manager"
require_value "MANAGER_A_PIN" "MANAGER_A_PIN (4 digits)" 1
company_a_resp="$(
  call_function "create_company_with_manager" "$PA_TOKEN" "$(
    jq -cn \
      --arg companyName "$COMPANY_A_NAME" \
      --arg companyCode "$COMPANY_A_CODE" \
      --arg managerUsername "$MANAGER_A_USERNAME" \
      --arg managerPin "$MANAGER_A_PIN" \
      '{companyName:$companyName, companyCode:$companyCode, managerUsername:$managerUsername, managerPin:$managerPin}'
  )"
)"
COMPANY_A_ID="$(echo "$company_a_resp" | jq -r '.companyId // empty')"
if [[ -z "${COMPANY_A_ID}" ]]; then
  print_redacted_json "create_company_with_manager failed (Company A)" "$company_a_resp"
  exit 1
fi
echo "   Company A id: ${COMPANY_A_ID}"

echo ""
echo "3) Create Company B + Manager B via Edge Function create_company_with_manager"
require_value "MANAGER_B_PIN" "MANAGER_B_PIN (4 digits)" 1
company_b_resp="$(
  call_function "create_company_with_manager" "$PA_TOKEN" "$(
    jq -cn \
      --arg companyName "$COMPANY_B_NAME" \
      --arg companyCode "$COMPANY_B_CODE" \
      --arg managerUsername "$MANAGER_B_USERNAME" \
      --arg managerPin "$MANAGER_B_PIN" \
      '{companyName:$companyName, companyCode:$companyCode, managerUsername:$managerUsername, managerPin:$managerPin}'
  )"
)"
COMPANY_B_ID="$(echo "$company_b_resp" | jq -r '.companyId // empty')"
if [[ -z "${COMPANY_B_ID}" ]]; then
  print_redacted_json "create_company_with_manager failed (Company B)" "$company_b_resp"
  exit 1
fi
echo "   Company B id: ${COMPANY_B_ID}"

echo ""
echo "4) Verify Company A row exists (platform_admin select)"
company_a_row="$(rest_select "$PA_TOKEN" "companies?companyCode=eq.${COMPANY_A_CODE}&select=id,companyCode,companyName,company_code")"
echo "$company_a_row" | jq '.'

echo ""
echo "5) Sign in as Manager A"
ma_email="$(internal_email "${COMPANY_A_CODE}" "${MANAGER_A_USERNAME}")"
ma_auth="$(auth_password_grant "$ma_email" "$MANAGER_A_PIN")"
MA_TOKEN="$(echo "$ma_auth" | jq -r '.access_token // empty')"
MA_USER_ID="$(echo "$ma_auth" | jq -r '.user.id // empty')"
if [[ -z "${MA_TOKEN}" || -z "${MA_USER_ID}" ]]; then
  print_redacted_json "Failed to sign in as Manager A" "$ma_auth"
  exit 1
fi
echo "   Manager A auth user id: ${MA_USER_ID}"

echo ""
echo "6) Create Employee 1 row (manager direct insert)"
employee_1_row="$(
  rest_insert "$MA_TOKEN" "employees" "$(
    jq -cn \
      --arg companyCode "$COMPANY_A_CODE" \
      --arg name "E2E Employee 1" \
      --arg contact "test-${ts}@example.invalid" \
      '{companyCode:$companyCode, name:$name, contact:$contact, active:true}'
  )"
)"
EMPLOYEE_1_ID="$(echo "$employee_1_row" | jq -r '.[0].id // empty')"
if [[ -z "${EMPLOYEE_1_ID}" ]]; then
  echo "Failed to insert Employee 1. Response:" >&2
  echo "$employee_1_row" | jq '.' >&2
  exit 1
fi
echo "   Employee 1 id: ${EMPLOYEE_1_ID}"

echo ""
echo "7) Create Employee 1 login via Edge Function create_employee_login"
require_value "EMPLOYEE_1_PIN" "EMPLOYEE_1_PIN (4 digits)" 1
employee_1_login_resp="$(
  call_function "create_employee_login" "$MA_TOKEN" "$(
    jq -cn \
      --arg companyCode "$COMPANY_A_CODE" \
      --arg employeeId "$EMPLOYEE_1_ID" \
      --arg username "$EMPLOYEE_1_USERNAME" \
      --arg pin "$EMPLOYEE_1_PIN" \
      '{companyCode:$companyCode, employeeId:$employeeId, username:$username, pin:$pin}'
  )"
)"
if [[ "$(echo "$employee_1_login_resp" | jq -r '.username // empty')" != "$EMPLOYEE_1_USERNAME" ]]; then
  print_redacted_json "create_employee_login failed (Employee 1)" "$employee_1_login_resp"
  exit 1
fi
echo "   Employee 1 login created/updated (username only; PIN not printed)."

echo ""
echo "8) Create Employee 2 row + login (for employee RLS isolation test)"
employee_2_row="$(
  rest_insert "$MA_TOKEN" "employees" "$(
    jq -cn \
      --arg companyCode "$COMPANY_A_CODE" \
      --arg name "E2E Employee 2" \
      --arg contact "test2-${ts}@example.invalid" \
      '{companyCode:$companyCode, name:$name, contact:$contact, active:true}'
  )"
)"
EMPLOYEE_2_ID="$(echo "$employee_2_row" | jq -r '.[0].id // empty')"
if [[ -z "${EMPLOYEE_2_ID}" ]]; then
  echo "Failed to insert Employee 2. Response:" >&2
  echo "$employee_2_row" | jq '.' >&2
  exit 1
fi
require_value "EMPLOYEE_2_PIN" "EMPLOYEE_2_PIN (4 digits)" 1
employee_2_login_resp="$(
  call_function "create_employee_login" "$MA_TOKEN" "$(
    jq -cn \
      --arg companyCode "$COMPANY_A_CODE" \
      --arg employeeId "$EMPLOYEE_2_ID" \
      --arg username "$EMPLOYEE_2_USERNAME" \
      --arg pin "$EMPLOYEE_2_PIN" \
      '{companyCode:$companyCode, employeeId:$employeeId, username:$username, pin:$pin}'
  )"
)"
if [[ "$(echo "$employee_2_login_resp" | jq -r '.username // empty')" != "$EMPLOYEE_2_USERNAME" ]]; then
  print_redacted_json "create_employee_login failed (Employee 2)" "$employee_2_login_resp"
  exit 1
fi
echo "   Employee 2 created (id: ${EMPLOYEE_2_ID})."

echo ""
echo "9) Create Job Site (manager direct insert)"
job_site_row="$(
  rest_insert "$MA_TOKEN" "job_sites" "$(
    jq -cn \
      --arg companyCode "$COMPANY_A_CODE" \
      --arg name "E2E Site" \
      --arg address "E2E Address" \
      '{companyCode:$companyCode, name:$name, address:$address, active:true}'
  )"
)"
JOB_SITE_ID="$(echo "$job_site_row" | jq -r '.[0].id // empty')"
if [[ -z "${JOB_SITE_ID}" ]]; then
  echo "Failed to insert Job Site. Response:" >&2
  echo "$job_site_row" | jq '.' >&2
  exit 1
fi
echo "   Job site id: ${JOB_SITE_ID}"

echo ""
echo "10) Create Schedule (manager direct insert)"
WEEK_START_DATE="$(date -u -d 'monday this week' +%F)"
schedule_row="$(
  rest_insert "$MA_TOKEN" "schedules" "$(
    jq -cn \
      --arg company_code "$COMPANY_A_CODE" \
      --arg week_start_date "$WEEK_START_DATE" \
      '{company_code:$company_code, week_start_date:$week_start_date}'
  )"
)"
SCHEDULE_ID="$(echo "$schedule_row" | jq -r '.[0].id // empty')"
if [[ -z "${SCHEDULE_ID}" ]]; then
  echo "Failed to insert Schedule. Response:" >&2
  echo "$schedule_row" | jq '.' >&2
  exit 1
fi
echo "   Schedule id: ${SCHEDULE_ID} (week_start_date=${WEEK_START_DATE})"

echo ""
echo "11) Create Shift for Employee 1 (manager direct insert)"
shift_1_row="$(
  rest_insert "$MA_TOKEN" "shifts" "$(
    jq -cn \
      --arg companyCode "$COMPANY_A_CODE" \
      --arg date "$WEEK_START_DATE" \
      --arg start "08:00:00" \
      --arg end "17:00:00" \
      --arg notes "E2E Shift 1" \
      --arg locId "$JOB_SITE_ID" \
      --arg empId "$EMPLOYEE_1_ID" \
      --arg schedule_id "$SCHEDULE_ID" \
      '{companyCode:$companyCode, date:$date, start:$start, end:$end, notes:$notes, locId:$locId, empId:$empId, schedule_id:$schedule_id}'
  )"
)"
SHIFT_1_ID="$(echo "$shift_1_row" | jq -r '.[0].id // empty')"
if [[ -z "${SHIFT_1_ID}" ]]; then
  echo "Failed to insert Shift 1. Response:" >&2
  echo "$shift_1_row" | jq '.' >&2
  exit 1
fi
echo "   Shift 1 id: ${SHIFT_1_ID}"

echo ""
echo "12) Create Shift for Employee 2 (manager direct insert)"
shift_2_row="$(
  rest_insert "$MA_TOKEN" "shifts" "$(
    jq -cn \
      --arg companyCode "$COMPANY_A_CODE" \
      --arg date "$WEEK_START_DATE" \
      --arg start "09:00:00" \
      --arg end "12:00:00" \
      --arg notes "E2E Shift 2" \
      --arg locId "$JOB_SITE_ID" \
      --arg empId "$EMPLOYEE_2_ID" \
      --arg schedule_id "$SCHEDULE_ID" \
      '{companyCode:$companyCode, date:$date, start:$start, end:$end, notes:$notes, locId:$locId, empId:$empId, schedule_id:$schedule_id}'
  )"
)"
SHIFT_2_ID="$(echo "$shift_2_row" | jq -r '.[0].id // empty')"
if [[ -z "${SHIFT_2_ID}" ]]; then
  echo "Failed to insert Shift 2. Response:" >&2
  echo "$shift_2_row" | jq '.' >&2
  exit 1
fi
echo "   Shift 2 id: ${SHIFT_2_ID}"

echo ""
echo "13) Employee RLS test: Employee 1 should only see their own shifts"
e1_email="$(internal_email "${COMPANY_A_CODE}" "${EMPLOYEE_1_USERNAME}")"
e1_auth="$(auth_password_grant "$e1_email" "$EMPLOYEE_1_PIN")"
E1_TOKEN="$(echo "$e1_auth" | jq -r '.access_token // empty')"
E1_USER_ID="$(echo "$e1_auth" | jq -r '.user.id // empty')"
if [[ -z "${E1_TOKEN}" || -z "${E1_USER_ID}" ]]; then
  print_redacted_json "Failed to sign in as Employee 1" "$e1_auth"
  exit 1
fi
e1_shifts="$(rest_select "$E1_TOKEN" "shifts?select=id,employee_id,empId,company_code,companyCode&order=date.desc")"
echo "$e1_shifts" | jq '.'
e1_count="$(echo "$e1_shifts" | jq 'length')"
if [[ "$e1_count" -ne 1 ]]; then
  echo "Expected Employee 1 to see exactly 1 shift, saw: $e1_count" >&2
  exit 1
fi
if [[ "$(echo "$e1_shifts" | jq -r '.[0].id')" != "$SHIFT_1_ID" ]]; then
  echo "Expected Employee 1 to see SHIFT_1_ID only." >&2
  exit 1
fi
echo "   OK: Employee 1 only sees their own shift."

echo ""
echo "14) Manager cross-company RLS test: Manager A should NOT read Company B data"
ma_read_company_b="$(rest_select "$MA_TOKEN" "companies?companyCode=eq.${COMPANY_B_CODE}&select=id,companyCode,companyName")"
echo "$ma_read_company_b" | jq '.'
if [[ "$(echo "$ma_read_company_b" | jq 'length')" -ne 0 ]]; then
  echo "Expected Manager A to see 0 rows for Company B." >&2
  exit 1
fi
echo "   OK: Manager A cannot read Company B."

echo ""
echo "Done."
echo "Summary (no PINs printed):"
echo "  Company A: code=${COMPANY_A_CODE} id=${COMPANY_A_ID}"
echo "  Manager A: username=${MANAGER_A_USERNAME} auth_user_id=${MA_USER_ID}"
echo "  Employee 1: employee_id=${EMPLOYEE_1_ID} username=${EMPLOYEE_1_USERNAME} auth_user_id=${E1_USER_ID}"
echo "  Employee 2: employee_id=${EMPLOYEE_2_ID} username=${EMPLOYEE_2_USERNAME}"
echo "  Job site: id=${JOB_SITE_ID}"
echo "  Schedule: id=${SCHEDULE_ID} week_start_date=${WEEK_START_DATE}"
echo "  Shifts: shift1_id=${SHIFT_1_ID} shift2_id=${SHIFT_2_ID}"
