#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${SUPABASE_PROJECT_REF:-}" ]]; then
  echo "Missing SUPABASE_PROJECT_REF env var." >&2
  exit 2
fi

if [[ -z "${SUPABASE_ANON_KEY:-}" ]]; then
  echo "Missing SUPABASE_ANON_KEY secret (set it in GitHub repo secrets)." >&2
  exit 2
fi

rm -rf dist
mkdir -p dist

rsync -a \
  --exclude=".git" \
  --exclude=".github" \
  --exclude="node_modules" \
  --exclude="supabase/.temp" \
  ./ dist/

mkdir -p dist/js dist/assets

cat > dist/js/config.js <<EOF
// GitHub Pages / static config (generated at deploy time).
//
// This file is intentionally generated by GitHub Actions so keys are not committed to git history.
// Never use the service role key in the browser.
export const SUPABASE_PROJECT_REF = "${SUPABASE_PROJECT_REF}";
export const SUPABASE_URL = "https://${SUPABASE_PROJECT_REF}.supabase.co";
export const SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}";
EOF

cat > dist/assets/config.js <<EOF
/* assets/config.js (generated at deploy time)
   This file is generated by GitHub Actions so keys are not committed to git history.
   Never use the service role key in the browser.
*/

// eslint-disable-next-line no-unused-vars
window.APP_CONFIG = {
  ...(window.APP_CONFIG || {}),
  USE_CLOUD: false,
  SUPABASE_URL: "https://${SUPABASE_PROJECT_REF}.supabase.co",
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}",
};
EOF
